#!/bin/bash

# Do stuff you need to do before original run script.

# Run the original run script.

#exec $S2I_SCRIPTS_PATH/run
touch > temp
npm install npm@latest -g
touch > temp1
npm init -f -y
touch temp2
npm install @slack/client --save
